#pragma once
#include <SFML/Graphics.hpp>
#include <vector>
#include "GameActor.h"

class Vigor : public GameActor
{
public:
	Vigor(std::vector<sf::Vector2f> data);
	~Vigor();
	virtual void draw(sf::RenderTarget& target);
	void Visualize();
	float PredictY(float xValue);
	void SinReg();

private:
	std::vector<sf::Vector2f> points; //input points
	std::vector<float> x; //x component of input
	std::vector<float> y; //y component of input
	sf::VertexArray regPoints; //Points generated by regression

	//y(x) = a * sin(x + b) + d
	float amplitude;
	float phaseShift;
	float midline;

};

