#pragma once
#include <SFML/Graphics.hpp>
#include <vector>
#include "GameActor.h"

class Vigor : public GameActor
{
public:
	Vigor(std::vector<sf::Vector2f> data);
	~Vigor();
	virtual void draw(sf::RenderTarget& target);
	void pack(sf::Packet& packet);
	bool checkIntersect(float x0, float y0, float x1, float y1);
	void Visualize();
	float PredictY(float xValue);
	bool SinReg();
	sf::VertexArray regPoints; //Points generated by regression

	float power;

private:
	bool hitEdge;
	int pixTraveled;

	bool swap;

	float mean(std::vector<float> values);
	void linReg();

	std::vector<sf::Vector2f> points; //input points
	std::vector<float> x; //x component of input
	std::vector<float> y; //y component of input

	//y(x) = a * sin((2pi/b)(x + c)) + d
	float amplitude;
	float period;
	float phaseShift;
	float midline;

	float currentX;

	float m, b, theta;
};

